### ISSUE TITLE
[question] 第一节课是早九，如何把早八改成早九

### ISSUE THREAD

**Issue by imqboy** [maoxig/nonebot-plugin-ai-timetable#2]
大佬你好，学校上午第一节课是早九，想问问该怎么改。
![image](https://user-images.githubusercontent.com/123036463/231509660-9ba26ae1-5238-47cb-b444-10923db680ae.png)
![image](https://user-images.githubusercontent.com/123036463/231509874-d58c654d-667c-49c5-a203-2e1fe5a86580.png)

**Comment by maoxig** [comment]
按理来说是不用改的，因为是第一节课，你发送/明日课表会包含这节课吗？或者说是本地课表没有更新？

**Comment by imqboy** [comment]
![22e38327b884daf2.jpg](https://user-images.githubusercontent.com/123036463/231513153-24bd1991-84b0-468d-aed0-48c2acba3797.jpg)
/明日课表 里有这个课程，但是发送/明日早八 提示没有

**Comment by maoxig** [comment]
> ![22e38327b884daf2.jpg](https://user-images.githubusercontent.com/123036463/231513153-24bd1991-84b0-468d-aed0-48c2acba3797.jpg) /明日课表 里有这个课程，但是发送/明日早八 提示没有

离谱，我这边测试没这个问题。你可以试着把这一行后面部分的判断改成别的试试，或许你这个是从0开始的？，
https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/8489ee62ac944582aca77fd7154f664c279a8664/nonebot_plugin_ai_timetable/utils.py#L248
比如改成
`if (courses["day"] == someday) and str(someweek) in courses["weeks"].split(",") and "2" in courses["sections"].split(","):`
因为我对比明日课表的判断
https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/8489ee62ac944582aca77fd7154f664c279a8664/nonebot_plugin_ai_timetable/utils.py#L133
唯一不同的就是后面这半句了
想不到还有什么可能出错了QAQ

**Comment by imqboy** [comment]
> > ![22e38327b884daf2.jpg](https://user-images.githubusercontent.com/123036463/231513153-24bd1991-84b0-468d-aed0-48c2acba3797.jpg) /明日课表 里有这个课程，但是发送/明日早八 提示没有
> 
> 离谱，我这边测试没这个问题。你可以试着把这一行后面部分的判断改成别的试试，或许你这个是从0开始的？，
> https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/8489ee62ac944582aca77fd7154f664c279a8664/nonebot_plugin_ai_timetable/utils.py#L248
> 比如改成
> `if (courses["day"] == someday) and str(someweek) in courses["weeks"].split(",") and "2" in courses["sections"].split(","):`
> 因为我对比明日课表的判断
> https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/8489ee62ac944582aca77fd7154f664c279a8664/nonebot_plugin_ai_timetable/utils.py#L133
> 唯一不同的就是后面这半句了
> 想不到还有什么可能出错了QAQ

好的，我去研究研究，感谢大佬( っ'-')

**Comment by maoxig** [comment]
> > > ![22e38327b884daf2.jpg](https://user-images.githubusercontent.com/123036463/231513153-24bd1991-84b0-468d-aed0-48c2acba3797.jpg) /明日课表 里有这个课程，但是发送/明日早八 提示没有
> > 
> > 
> > 离谱，我这边测试没这个问题。你可以试着把这一行后面部分的判断改成别的试试，或许你这个是从0开始的？，
> > https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/8489ee62ac944582aca77fd7154f664c279a8664/nonebot_plugin_ai_timetable/utils.py#L248
> > 
> > 比如改成
> > `if (courses["day"] == someday) and str(someweek) in courses["weeks"].split(",") and "2" in courses["sections"].split(","):`
> > 因为我对比明日课表的判断
> > https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/8489ee62ac944582aca77fd7154f664c279a8664/nonebot_plugin_ai_timetable/utils.py#L133
> > 
> > 唯一不同的就是后面这半句了
> > 想不到还有什么可能出错了QAQ
> 
> 好的，我去研究研究，感谢大佬( っ'-')


不用谢QAQ，如果还是找不到问题就只能翻`usertable.json`文件，看看这节课的数据到底长啥样的了，然后再看看要咋改
