### ISSUE TITLE
[Feature] 希望更新依赖httpx版本>=0.24.1

### ISSUE THREAD

**Issue by faithleysath** [maoxig/nonebot-plugin-ai-timetable#4]
nonebot-plugin-picstatus插件需要的httpx版本是">=0.24.1"，而nonebot-plugin-ai-timetable插件需要的httpx版本是">=0.23.0,<0.24.0"。这两个版本范围存在冲突，无法同时满足两个插件的依赖关系。
`
Because no versions of nonebot-plugin-picstatus match >0.5.1,<0.6.0
 and nonebot-plugin-picstatus (0.5.1) depends on httpx (>=0.24.1), nonebot-plugin-picstatus (>=0.5.1,<0.6.0) requires httpx (>=0.24.1).
And because nonebot-plugin-ai-timetable (0.3.4) depends on httpx (>=0.23.0,<0.24.0)
 and no versions of nonebot-plugin-ai-timetable match >0.3.4,<0.4.0, nonebot-plugin-picstatus (>=0.5.1,<0.6.0) is incompatible with nonebot-plugin-ai-timetable (>=0.3.4,<0.4.0).
So, because qq-bot depends on both nonebot-plugin-ai-timetable (^0.3.4) and nonebot-plugin-picstatus (^0.5.1), version solving failed.`

**Comment by maoxig** [comment]
已更新

**Comment by faithleysath** [comment]
(⁠人⁠*⁠´⁠∀⁠｀⁠)⁠｡⁠*ﾟ⁠+
