### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by purelolly** [maoxig/nonebot-plugin-ai-timetable#5]
现在有问题了，不能发送了图片连文字也没用

**Comment by maoxig** [comment]
方便提供一下日志或者报错信息吗？

**Comment by imqboy** [comment]
![image](https://github.com/maoxig/nonebot-plugin-ai-timetable/assets/123036463/90759910-df19-45a4-84b9-5730382347eb)
![image](https://github.com/maoxig/nonebot-plugin-ai-timetable/assets/123036463/22f3743a-53f6-497c-a43d-5a338111d139)
好像是有问题，也没有报错就是没反应了，不知道为啥

**Comment by imqboy** [comment]
> ![image](https://user-images.githubusercontent.com/123036463/265178610-90759910-df19-45a4-84b9-5730382347eb.png) ![image](https://user-images.githubusercontent.com/123036463/265178639-22f3743a-53f6-497c-a43d-5a338111d139.png) 好像是有问题，也没有报错就是没反应了，不知道为啥

数据也导入了
![image](https://github.com/maoxig/nonebot-plugin-ai-timetable/assets/123036463/3d06b373-7e3f-467b-9a50-2fe002aaa3b0)

**Comment by maoxig** [comment]
是否安装了[nonebot_plugin_htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)，也许是图片渲染出错了？

**Comment by maoxig** [comment]
我等下修一下

**Comment by maoxig** [comment]
已修复，可更新到0.3.6以解决该问题
