### ISSUE TITLE
还是有问题

### ISSUE THREAD

**Issue by purelolly** [maoxig/nonebot-plugin-ai-timetable#6]
获取课表获取不出来，导入成功了
并且也没错误信息，

**Comment by purelolly** [comment]
![1985689-1069222919-CBE09C295FBFAE7E33526B71F3F2D60C](https://github.com/maoxig/nonebot-plugin-ai-timetable/assets/78009999/ea35dcd3-fe04-4904-9ca2-698cd1298484)

**Comment by maoxig** [comment]
1. 这个图片是读取本地的数据生成的，如果查询`本周课表`没有问题的话，你可以检查一下本地`data/usertable.json`的数据是否有问题，可以试试用`更新课表`来更新本地的课表。
2. 也有可能是查询的那一天没有课，例如查询星期六的课表就会是这样。
3. 在导入课表前请确保登录了小米账户，否则可能无法获取到正确的用户课表
我这边bot测试了一下，没有出现这种情况，所以如果这些措施做完之后还是有问题，就可能需要麻烦一下你提供更加详细的信息以方便我定位错误，谢谢😘

**Comment by purelolly** [comment]
> 



> 1. 这个图片是读取本地的数据生成的，如果查询`本周课表`没有问题的话，你可以检查一下本地`data/usertable.json`的数据是否有问题，可以试试用`更新课表`来更新本地的课表。
> 2. 也有可能是查询的那一天没有课，例如查询星期六的课表就会是这样。
> 3. 在导入课表前请确保登录了小米账户，否则可能无法获取到正确的用户课表
>    我这边bot测试了一下，没有出现这种情况，所以如果这些措施做完之后还是有问题，就可能需要麻烦一下你提供更加详细的信息以方便我定位错误，谢谢😘

本周课没有问题，usertable有数据，就是没有，无论查那天都没有

**Comment by maoxig** [comment]
> > 
> 
> > 1. 这个图片是读取本地的数据生成的，如果查询`本周课表`没有问题的话，你可以检查一下本地`data/usertable.json`的数据是否有问题，可以试试用`更新课表`来更新本地的课表。
> > 2. 也有可能是查询的那一天没有课，例如查询星期六的课表就会是这样。
> > 3. 在导入课表前请确保登录了小米账户，否则可能无法获取到正确的用户课表
> >    我这边bot测试了一下，没有出现这种情况，所以如果这些措施做完之后还是有问题，就可能需要麻烦一下你提供更加详细的信息以方便我定位错误，谢谢😘
> 
> 本周课没有问题，usertable有数据，就是没有，无论查那天都没有

如果这一周的课都没有，那可能是周数计算或者设置错误了，因为查询课程的逻辑顺序是

1. 获取当前时间戳（因此，请检查你的系统是否时间正确）
2. 从本地获取开学时间戳，做差计算得到当前周数（因此请确保设置了正确的开始上课时间等）
3. 使用datetime获取当天周几，然后综合本周数和当天日期，从本地搜索得到相应的课程

根据你的描述，如果你之前还能正常使用，我猜测可能是你的开学时间或者某个设置出错了，这周本来应该是第1周，但计算出来的周数是0，于是插件认为这周没有课，所以不输出相应结果，

你可以尝试将
https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/a7254dc8ba69f248f9605c56a584fdf064ddfda6/nonebot_plugin_ai_timetable/utils.py#L183-L192
这里的`presentweek`打印出来以检验是否正确，例如在这一行后面加上
```python
print(presentweek)
```
来打印结果。
如果还不行，请提供更多信息以便于解决这个问题

**Comment by purelolly** [comment]
> > > 
> > 
> > 
> > > 1. 这个图片是读取本地的数据生成的，如果查询`本周课表`没有问题的话，你可以检查一下本地`data/usertable.json`的数据是否有问题，可以试试用`更新课表`来更新本地的课表。
> > > 2. 也有可能是查询的那一天没有课，例如查询星期六的课表就会是这样。
> > > 3. 在导入课表前请确保登录了小米账户，否则可能无法获取到正确的用户课表
> > >    我这边bot测试了一下，没有出现这种情况，所以如果这些措施做完之后还是有问题，就可能需要麻烦一下你提供更加详细的信息以方便我定位错误，谢谢😘
> > 
> > 
> > 本周课没有问题，usertable有数据，就是没有，无论查那天都没有
> 
> 如果这一周的课都没有，那可能是周数计算或者设置错误了，因为查询课程的逻辑顺序是
> 
> 1. 获取当前时间戳（因此，请检查你的系统是否时间正确）
> 2. 从本地获取开学时间戳，做差计算得到当前周数（因此请确保设置了正确的开始上课时间等）
> 3. 使用datetime获取当天周几，然后综合本周数和当天日期，从本地搜索得到相应的课程
> 
> 根据你的描述，如果你之前还能正常使用，我猜测可能是你的开学时间或者某个设置出错了，这周本来应该是第1周，但计算出来的周数是0，于是插件认为这周没有课，所以不输出相应结果，
> 
> 你可以尝试将
> 
> https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/a7254dc8ba69f248f9605c56a584fdf064ddfda6/nonebot_plugin_ai_timetable/utils.py#L183-L192
> 
> 
> 这里的`presentweek`打印出来以检验是否正确，例如在这一行后面加上
> ```python
> print(presentweek)
> ```
> 
> 来打印结果。 如果还不行，请提供更多信息以便于解决这个问题

不是我已经有段时间没用了，我怎么形容呢，若你有时间可以自己试试

**Comment by purelolly** [comment]
> > > > 
> > > 
> > > 
> > > > 1. 这个图片是读取本地的数据生成的，如果查询`本周课表`没有问题的话，你可以检查一下本地`data/usertable.json`的数据是否有问题，可以试试用`更新课表`来更新本地的课表。
> > > > 2. 也有可能是查询的那一天没有课，例如查询星期六的课表就会是这样。
> > > > 3. 在导入课表前请确保登录了小米账户，否则可能无法获取到正确的用户课表
> > > >    我这边bot测试了一下，没有出现这种情况，所以如果这些措施做完之后还是有问题，就可能需要麻烦一下你提供更加详细的信息以方便我定位错误，谢谢😘
> > > 
> > > 
> > > 本周课没有问题，usertable有数据，就是没有，无论查那天都没有
> > 
> > 
> > 如果这一周的课都没有，那可能是周数计算或者设置错误了，因为查询课程的逻辑顺序是
> > 
> > 1. 获取当前时间戳（因此，请检查你的系统是否时间正确）
> > 2. 从本地获取开学时间戳，做差计算得到当前周数（因此请确保设置了正确的开始上课时间等）
> > 3. 使用datetime获取当天周几，然后综合本周数和当天日期，从本地搜索得到相应的课程
> > 
> > 根据你的描述，如果你之前还能正常使用，我猜测可能是你的开学时间或者某个设置出错了，这周本来应该是第1周，但计算出来的周数是0，于是插件认为这周没有课，所以不输出相应结果，
> > 你可以尝试将
> > https://github.com/maoxig/nonebot-plugin-ai-timetable/blob/a7254dc8ba69f248f9605c56a584fdf064ddfda6/nonebot_plugin_ai_timetable/utils.py#L183-L192
> > 
> > 这里的`presentweek`打印出来以检验是否正确，例如在这一行后面加上
> > ```python
> > print(presentweek)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 来打印结果。 如果还不行，请提供更多信息以便于解决这个问题
> 
> 不是我已经有段时间没用了，我怎么形容呢，若你有时间可以自己试试

已经好了 没有设置开始上课时间
