### ISSUE TITLE
图片输出为乱码

### ISSUE THREAD

**Issue by zero24345** [maoxig/nonebot-plugin-ai-timetable#7]
![988381e620ec88f6f1821f6b1b4da5d5](https://github.com/maoxig/nonebot-plugin-ai-timetable/assets/114745061/1c0194f8-92ad-449b-92a6-2f419718e8eb)

**Comment by maoxig** [comment]
请根据插件[nonebot_plugin_htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)下面的说明为你的系统安装正确的字体
